spring:
  application:
    name: Besties-demo

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db:3306/beasties_db?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:beasties_user}
    password: ${SPRING_DATASOURCE_PASSWORD:beasties_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  validity-ms: 86400000